### ISSUE TITLE
Teletraan deploy-agent is unable to find aws_access_key_id within configuration file. 

### ISSUE THREAD

**Issue by brennentsmith** [pinterest/teletraan#125]
When the deploy agent is run with a s3:// url, it is unable to find the `aws_access_key_id` and fails to perform the deploy. 

`aws_access_key_id` and `aws_secret_access_key` are correctly defined within the configuration file, and other directives within the configuration file are correctly parsed (not falling back to defaults).

Command being used:
`/usr/local/bin/deploy-agent -f /etc/deployagent.conf`

Copy of `/etc/deployagent.conf` (sensitive parts redacted):
```
[default_config]
deploy_agent_dir = /data/deployd/
target_default_dir = /tmp
builds_dir = /data/deployd/builds
log_directory = /data/deployd/logs
log_level = DEBUG
process_wait_interval = 2
process_timeout = 1800
min_running_time = 60
back_off_factor = 2
max_sleep_interval = 60
num_builds_to_retain = 2
package_format = tar.gz
max_retry = 3
max_tail_bytes = 10240
aws_access_key_id = AKAAAAAAAAAAAAAALQ
aws_secret_access_key =  x9aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaanP
teletraan_service_url = http://172.1.1.1:8080
teletraan_service_version = v1
# teletraan_service_token = test
```

Error log message received:
```
INFO:deployd.common.executor:Failed: deploy-downloader -f /etc/deployagent.conf -v yb9mGyjqQtuxsNvGiFhtOQ_b3fac1c -u s3://s3-us-west-2.amazonaws.com/ookla/artifact.tgz -e Speedtest-Intelligence, at 2 retry. Error:
INFO:deployd.download.downloader:Start to download the package.
Traceback (most recent call last):
  File "/usr/local/bin/deploy-downloader", line 9, in <module>
    load_entry_point('deploy-agent==1.2.5', 'console_scripts', 'deploy-downloader')()
  File "build/bdist.linux-x86_64/egg/deployd/download/downloader.py", line 113, in main
  File "build/bdist.linux-x86_64/egg/deployd/download/downloader.py", line 56, in download
  File "build/bdist.linux-x86_64/egg/deployd/download/download_helper_factory.py", line 33, in gen_downloader
  File "build/bdist.linux-x86_64/egg/deployd/common/config.py", line 187, in get_aws_access_key
  File "build/bdist.linux-x86_64/egg/deployd/common/config.py", line 131, in get_var
deployd.common.exceptions.DeployConfigException: aws_access_key_id cannot be found.
DEBUG:deployd.common.executor:start: 2016-04-20 21:58:20.442645, now: 2016-04-20 21:58:30.456953, process: 10
DEBUG:deployd.common.executor:start: 2016-04-20 21:58:20.442645, now: 2016-04-20 21:58:30.458551, process: 10
```

**Comment by yujunglo** [comment]
Hi Brennen,
Thanks for the question. We have released deploy-agent 1.2.6 to fix this problem. 
Thanks.

**Comment by brennentsmith** [comment]
Excellent - Thank you @yujunglo! S3 downloads are working properly now! I did run into a very similar issue during the `Staging` deployStage - it's unable to retrieve the correct `user_role` (despite the fact that this should fallback to `getpass.getuser()`). I added the `user_role = root` directive to the config specified above to no avail. Respective error message below:

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 172.1.1.1
DEBUG:requests.packages.urllib3.connectionpool:"POST /v1/system/ping HTTP/1.1" 200 35
DEBUG:deployd.client.client:PingRequest(hostId=idtest, hostName=ip-172-1-1-1, hostIp=198.1.1.11, groups=['test', 'test2'], reports=PingReport(deployId=JJDC4PCzS6GO5Qb-YHGfeQ, envId=scn8tLT5SqWEi4-iLG4_wg, deployStage=STAGING, status=TOO_MANY_RETRY, errorCode=1), errorMessage=INFO:deployd.staging.stager:Start to stage the package.
Traceback (most recent call last):
  File "/usr/local/bin/deploy-stager", line 9, in <module>
    load_entry_point('deploy-agent==1.2.5', 'console_scripts', 'deploy-stager')()
  File "build/bdist.linux-x86_64/egg/deployd/staging/stager.py", line 139, in main
  File "build/bdist.linux-x86_64/egg/deployd/staging/stager.py", line 37, in __init__
  File "build/bdist.linux-x86_64/egg/deployd/common/config.py", line 166, in get_user_role
  File "build/bdist.linux-x86_64/egg/deployd/common/config.py", line 123, in get_var
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'user_role' in section: 'default_config', failCount=3, extraInfo=None, deployAlias=None)) -> PingResponse(opCode=NOOP, deployGoal=None)
INFO:deployd.agent:No deploy goal to be updated.
INFO:deployd.agent:Complete the current deploy with response: PingResponse(opCode=NOOP, deployGoal=None).
```

If you wish, I would be happy to open a separate issue instead of appending to this one. I simply figured that it is a very similar issue, it is most likely related.

**Comment by brennentsmith** [comment]
Ah it's just the `except Exception` on line: https://github.com/pinterest/teletraan/blob/master/deploy-agent/deployd/common/config.py#L128 - I'll just submit a PR

**Comment by yujunglo** [comment]
Hey Brennen,
Thanks for following up! Looking at your stack trace, it seems your code is pretty old (the config.py line 166 doesn't match). Could you please update your deploy-agent to 1.2.6? Thanks.

**Comment by brennentsmith** [comment]
Hi @yujunglo,

I could have sworn I did a clean pull/build/install after 1.2.6, but it appears that I was incorrect! So sorry for bringing up the second issue, and thank you for the quick help and open sourcing Teletraan - it's an awesome deploy tool. :)
