### ISSUE TITLE
error while creating env

### ISSUE THREAD

**Issue by betterltn** [pinterest/teletraan#247]
Am getting following error while trying to add  new enviornment

Teletraan failed to call backend server. Contact your friendly Teletraan owners for assistance. Hint: 500, Message: Cannot create PoolableConnectionFactory (Unknown database 'deploy')

Traceback (most recent call last): File "/root/teletraan-demo/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response response = wrapped_callback(request, _callback_args, *_callback_kwargs) File "/root/teletraan-demo/deploy-board/deploy_board/webapp/env_views.py", line 566, in post_create_env environs_helper.create_env(request, data) File "/root/teletraan-demo/deploy-board/deploy_board/webapp/helpers/environs_helper.py", line 92, in create_env return deployclient.post("/envs", request.teletraan_user_id.token, data=data) File "/root/teletraan-demo/deploy-board/deploy_board/webapp/helpers/deployclient.py", line 78, in post return self.__call('post')(path, token, params=params, data=data) File "/root/teletraan-demo/deploy-board/deploy_board/webapp/helpers/decorators.py", line 67, in f_retry return f(_args, *_kwargs) File "/root/teletraan-demo/deploy-board/deploy_board/webapp/helpers/deployclient.py", line 65, in api "Hint: %s, %s" % (response.status_code, response.content)) TeletraanException: Teletraan failed to call backend server. Contact your friendly Teletraan owners for assistance. Hint: 500, Message: Cannot create PoolableConnectionFactory (Unknown database 'deploy')

**Comment by sbaogang** [comment]
Thanks for reporting, will get back to you

**Comment by sbaogang** [comment]
can you tell which doc you were following? looks like you did not have the database created, maybe  certain step is missing in the doc.
